contadoria_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: aws-1-sa-east-1.pooler.supabase.com
      user: postgres.owpqwkntxojqnpyfebal
      password: "Nk6/4Q-_Aq8ukW!"
      port: 6543
      dbname: postgres
      schema: public
      threads: 4
